# Generated by Django 4.2.7 on 2024-06-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.order'),
        ),
    ]
