# Generated by Django 5.0.6 on 2024-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetailsmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee/media/%Y/%m/%d/'),
        ),
    ]
