# Generated by Django 5.0.6 on 2024-05-16 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOccasionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_occasion', models.DateField()),
                ('end_occasion', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.branch')),
            ],
        ),
    ]
