# Generated by Django 5.0.6 on 2024-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeemodel_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
