# Generated by Django 5.0.6 on 2024-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_otp_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
